# Generated by Django 5.0.4 on 2025-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_userprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, default='beginner', max_length=50, null=True),
        ),
    ]
