# Generated by Django 5.0.4 on 2025-12-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(choices=[('stepik_api', 'Stepik API'), ('user_added', 'User Added')], default='stepik_api', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='stepik_url',
            field=models.URLField(blank=True, help_text='Full Stepik course URL'),
        ),
    ]
