# Generated by Django 5.0.4 on 2025-12-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_source_course_stepik_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discipline_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memory_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_format',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio / Podcasts'), ('text', 'Text'), ('practice', 'Practice / Cases'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_pace',
            field=models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strategy_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('read_write', 'Read/Write'), ('kinesthetic', 'Kinesthetic'), ('mixed', 'Mixed')], default='visual', max_length=20),
        ),
    ]
