# Generated by Django 5.0.4 on 2025-12-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_learningstrategy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningstrategy',
            options={'verbose_name_plural': 'Learning Strategies'},
        ),
        migrations.RemoveField(
            model_name='learningstrategy',
            name='strategy_json',
        ),
        migrations.AddField(
            model_name='learningstrategy',
            name='format_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='learningstrategy',
            name='pace',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningstrategy',
            name='steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='learningstrategy',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningstrategy',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='learningstrategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='courses.userprofile'),
        ),
    ]
