# Generated by Django 5.0.4 on 2025-12-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_learningstrategy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pace',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('read_write', 'Read/Write'), ('kinesthetic', 'Kinesthetic'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
    ]
